### ISSUE TITLE
How to distribute GTK Ruby application

### ISSUE THREAD

**Issue by JijoBose** [ruby-gnome2/ruby-gnome2#1005]
I've created an application using **GTK3** and **Ruby** :gem: 
Could someone please explain me how to distribute my application to users across Linux and Mac.

Thanks

**Comment by cedlemo** [comment]
The best way is to create a gem, here are two applications I have created where you can see how I do it:

*  https://github.com/cedlemo/gifshouldbedead
*  https://github.com/cedlemo/topinambour

In each I have created a simple myapp.gemspec file. It is with this file that you create your gem with the following command : 

    gem build topinambour.gemspec

Then you will need to create an account in rubygems.org and [push it](http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg).  

Here is the main reference in order to build your own gem : http://guides.rubygems.org/

**Comment by JijoBose** [comment]
Thank you :+1:  so much for the instructions @cedlemo ,Yes I think that's the best way to do for now.

BTW users would have to install Ruby :gem:  to use the app, It would have been nice if users could download the **.deb/.tar.xz** packages to install the application in Ubuntu/Linux :penguin: .
Are there any tutorials or methods to create **.deb** or **.tar.xz** packages?
