### ISSUE TITLE
ruby-gdk-pixbuf2: cannot overwrite Pixbuf.pixels with substitution

### ISSUE THREAD

**Issue by dai-vdr** [ruby-gnome2/ruby-gnome2#1138]
forwarded from: https://bugs.debian.org/840909

----

I'm trying to make ninix-aya work with Ruby-GNOME2 3.0.9.
But I found that I cannot overwrite Pixbuf.pixels with substitution.

```ruby
pix = GdkPixbuf::Pixbuf.new(:file => "test.png")
pix.pixels[0]
=> 0
pix.pixels[0] = 255
=> 255
pix.pixels[0]
=> 0
```

In 2.2.5 I can modify GdkPixbuf through pixels. 
Is there any API change?

**Comment by kou** [comment]
You can't change pixbuf data through `GdkPixbuf::Pixbuf#pixels` with both 2.2.5 and 3.0.9. Because Ruby's `String` copied original data. It doesn't reuse external data.

It's a good idea that we support modifying pixbuf data through an object (not `String`) returned by `GdkPixbuf::Pixbuf#pixels`. But it's not out of this issue.

**Comment by dai-vdr** [comment]
thanks. i will send it to original reporter.
