### ISSUE TITLE
 *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated

### ISSUE THREAD

**Issue by PeterWAWood** [ruby-gnome2/ruby-gnome2#400]
When launching Ruby/gkt3 scripts on OS X (10.10.3 in my case), the following warning message is displayed in the console:

```
2015-05-05 11:47:24.580 ruby[34656:4812590] *** WARNING: Method userSpaceScaleFactor in class NSView is deprecated on 10.7 and later. It should not be used in new applications. Use convertRectToBacking: instead. 
```

**Comment by kou** [comment]
Thanks for your report.
It's GTK+ problem not Ruby/GTK3. Could you report it to https://bugzilla.gnome.org/ ?

It may be better that you refer https://bugzilla.gnome.org/show_bug.cgi?id=639826 as a related bug because the patch https://gist.github.com/zwaldowski/3388768 referred from https://bugzilla.gnome.org/show_bug.cgi?id=639826#c2 may resolve the warning message.

**Comment by PeterWAWood** [comment]
Thanks for the response. I will report the issue on the gnome/org bugzilla as you suggest.

**Comment by kou** [comment]
Thanks! I found your bug report: https://bugzilla.gnome.org/show_bug.cgi?id=749004
